"""
Pokemon Object Representation
"""
from collections import defaultdict
from uuid import uuid4

from engine.base import Component

DEFAULT_XP_GAIN = 50.0


class TmManager(Component):
    """
    Records Pokemon TM (Technical Machine) move modifications
    """

    CONFIG_PATH = 'engine/data/tm_movesets.txt'

    def initialize(self):
        """
        Load default TMs for all Pokemon
        """
        super().initialize()
        with open(self.CONFIG_PATH, 'r') as tm_movesets_file:
            tm_movesets_raw = tm_movesets_file.readlines()

        self.tm_movesets = defaultdict(lambda: "RETURN")
        for row in tm_movesets_raw:
            pokemon, tm_move = row.split()
            self.tm_movesets[pokemon] = tm_move.strip().upper()

    def get_tm_move(self, pokemon):
        """
        Get a TM move for a Pokemon
        """
        return self.tm_movesets[pokemon]


class PokemonFactory(Component):
    """
    Supports creating Pokemon instances
    """

    CONFIG_PATH = 'engine/data/default_movesets.txt'

    def initialize(self):
        """
        Load default movesets for all Pokemon when instantiating them.
        """
        super().initialize()
        with open(self.CONFIG_PATH, 'r') as default_movesets_file:
            default_movesets_raw = default_movesets_file.readlines()

        self.default_movesets = {}  # maps pokemon name to default BattleCard
        for line in default_movesets_raw:
            pokemon_name = line.split(',')[0]
            self.default_movesets[pokemon_name] = line

    def get_default_battle_card(self, pokemon_name):
        """
        Load the default battle card for a Pokemon
        """
        return BattleCard.from_string(self.default_movesets[pokemon_name])

    def get_evolved_battle_card(self, evolved_form, battle_card):
        """
        Get an evolved battle card.

        Takes the original battle card and checks for tm_flag and shiny being set.
        These properties will be persisted to the new card.
        """
        evolved_card = BattleCard.from_string(self.default_movesets[evolved_form])
        if battle_card.shiny:
            evolved_card.make_shiny()
        if battle_card.tm_flag:
            tm_move = self.state.tm_manager.get_tm_move(evolved_form)
            evolved_card.set_tm_move(tm_move)

        return evolved_card

    def create_pokemon_by_name(self, pokemon_name):
        """
        Create a new Pokemon by pokemon name.

        Example, pass in `pikachu` to create a default Pikachu.
        """
        battle_card = self.get_default_battle_card(pokemon_name)
        return Pokemon(pokemon_name, battle_card)


class EvolutionManager(Component):
    """
    Pokemon Evolution Manager
    """

    def initialize(self):
        pass

    def get_evolution(self, pokemon_name):
        """
        Look up the evolution of a Pokemon by name
        """
        pass

    def turn_cleanup(self):
        for player in self.state.players:
            if not player.is_alive:
                continue
            for idx, party_member in enumerate(player.party):
                party_member.add_xp()
                if party_member.xp > threshold:
                    # look up the evolution of a pokemon
                    evolved_form = self.get_evolution(party_member.name)


class Pokemon:
    """
    Instantiate unique object based on name
    """

    def __init__(
        self,
        pokemon_name,
        battle_card,
        id=None,
    ):
        self.name = pokemon_name
        self.battle_card = battle_card
        self.id = id or uuid4()
        self.item = None
        self.xp = 0

    def __repr__(self):
        return "{} ({})".format(self.name, self.id)

    def add_xp(self, amount=DEFAULT_XP_GAIN):
        """
        Add experience to a Pokemon
        """
        self.xp += amount


class BattleCard:
    """
    Pokemon Combat Representation

    Each Pokemon should have this instantiated
    """

    SHINY_POWER_FACTOR = 1.3  # multiply attack and defense by this number

    def __init__(
        self,
        name,
        move_f,
        move_ch,
        move_tm,
        level,
        a_iv,
        d_iv,
        hp_iv,
        tm_flag=False,
        shiny=False,
    ):
        """
        Battle Card representation for a Pokemon.

        This should be generated by a Pokemon entry from a player roster and should be fed
        to the battle simulator.
        """
        self.name = name
        self.move_f = move_f
        self.move_ch = move_ch
        self.move_tm = move_tm
        self.level = int(level)
        self.a_iv = int(a_iv)
        self.d_iv = int(d_iv)
        self.hp_iv = int(hp_iv)
        self.tm_flag = tm_flag
        self.shiny = shiny

    def make_shiny(self):
        """
        Mark a Pokemon as shiny and adjust stats.

        Does nothing if the Pokemon is already shiny.
        """
        if self.shiny:
            return False
        self.shiny = True
        self.a_iv *= self.SHINY_POWER_FACTOR
        self.d_iv *= self.SHINY_POWER_FACTOR
        return True

    def set_tm_move(self, move):
        """
        Add a TM move to a Pokemon

        Does nothing if the Pokemon already has a TM move.
        """
        if self.tm_flag:
            return False
        self.tm_flag = True
        self.move_tm = move.lower()
        return True

    @classmethod
    def from_string(cls, string):
        """
        Parse from a comma-delimited string

        This will initialize as a default.
        """
        l = string.split(',')
        return BattleCard(
            name = l[0],
            move_f = l[1],
            move_ch = l[2],
            move_tm = l[3],
            level = l[4],
            a_iv = l[5], 
            d_iv = l[6], 
            hp_iv = l[7],
            tm_flag = 0,
            shiny = 0
        )

    def to_string(self):
        """
        Return a PvPoke string representation of the Pokemon
        """
        return ",".join(str(x) for x in [
            self.name,
            self.move_f,
            self.move_ch,
            self.move_tm,
            self.level,
            self.a_iv,
            self.d_iv,
            self.hp_iv,
        ])
